# Generated by Django 5.2.3 on 2025-07-04 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_comment_replies_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['updated_at', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='main_commen_post_id_924827_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='main_commen_user_id_7e96e2_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='main_commen_post_id_a5ec46_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'created_at'], name='main_commen_user_id_b68d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['updated_at'], name='main_commen_updated_60323c_idx'),
        ),
    ]
